services:
  taggingai:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: taggingai
    ports:
      - "8002:80"
    volumes:
      - .:/app
    env_file:
      - .env
    restart: unless-stopped